-- The timeline tables for PostgreSQL, matching src/server/sql/schema.ts.
-- Replace the tlg_ prefix everywhere if the store is configured with another one.

CREATE TABLE IF NOT EXISTS tlg_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    reference_id TEXT NULL,
    impact TEXT NOT NULL,
    scope TEXT NULL,
    external_id TEXT NULL
);

CREATE INDEX IF NOT EXISTS tlg_incidents_external ON tlg_incidents(external_id);

CREATE TABLE IF NOT EXISTS tlg_incident_classifications (
    incident_id BIGINT NOT NULL REFERENCES tlg_incidents(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (incident_id, position)
);

CREATE TABLE IF NOT EXISTS tlg_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL REFERENCES tlg_incidents(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT NULL,
    kind TEXT NOT NULL,
    side TEXT NOT NULL,
    parent_id BIGINT NULL REFERENCES tlg_nodes(id) ON DELETE CASCADE,
    identifier TEXT NULL,
    role TEXT NULL,
    criticality TEXT NOT NULL,
    compromised SMALLINT NOT NULL,
    icon TEXT NULL,
    color_override TEXT NULL,
    external_id TEXT NULL,
    canonical_key TEXT NULL
);
CREATE INDEX IF NOT EXISTS tlg_nodes_incident ON tlg_nodes(incident_id);
CREATE INDEX IF NOT EXISTS tlg_nodes_canonical ON tlg_nodes(canonical_key);

CREATE TABLE IF NOT EXISTS tlg_node_layouts (
    node_id BIGINT NOT NULL REFERENCES tlg_nodes(id) ON DELETE CASCADE,
    representation TEXT NOT NULL,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (node_id, representation)
);

CREATE TABLE IF NOT EXISTS tlg_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL REFERENCES tlg_incidents(id) ON DELETE CASCADE,
    timestamp TEXT NOT NULL,
    end_timestamp TEXT NULL,
    time_known SMALLINT NOT NULL,
    order_index INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT NULL,
    side TEXT NOT NULL,
    attack_tactic TEXT NOT NULL,
    response_phase TEXT NOT NULL,
    mitre_technique_id TEXT NULL,
    severity TEXT NOT NULL,
    confidence TEXT NOT NULL,
    outcome TEXT NOT NULL,
    audience TEXT NOT NULL,
    evidence_source TEXT NULL,
    is_milestone SMALLINT NOT NULL,
    icon TEXT NULL,
    source_node_id BIGINT NULL REFERENCES tlg_nodes(id) ON DELETE SET NULL,
    target_node_id BIGINT NULL REFERENCES tlg_nodes(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS tlg_steps_incident ON tlg_steps(incident_id);
CREATE INDEX IF NOT EXISTS tlg_steps_timestamp ON tlg_steps(timestamp);

CREATE TABLE IF NOT EXISTS tlg_step_involvements (
    step_id BIGINT NOT NULL REFERENCES tlg_steps(id) ON DELETE CASCADE,
    node_id BIGINT NOT NULL REFERENCES tlg_nodes(id) ON DELETE CASCADE,
    involvement TEXT NOT NULL,
    PRIMARY KEY (step_id, node_id)
);

CREATE TABLE IF NOT EXISTS tlg_step_tags (
    step_id BIGINT NOT NULL REFERENCES tlg_steps(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (step_id, position)
);

CREATE TABLE IF NOT EXISTS tlg_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT NOT NULL REFERENCES tlg_incidents(id) ON DELETE CASCADE,
    source_node_id BIGINT NOT NULL REFERENCES tlg_nodes(id) ON DELETE CASCADE,
    target_node_id BIGINT NOT NULL REFERENCES tlg_nodes(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    label TEXT NULL,
    confidence TEXT NOT NULL,
    step_id BIGINT NULL REFERENCES tlg_steps(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS tlg_links_incident ON tlg_links(incident_id);
